# Generated by Django 6.0.3 on 2026-04-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('movilidad', 'Movilidad'), ('reaccion', 'Reacción'), ('saque', 'Saque'), ('recepcion', 'Recepción')], default='movilidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('nombre', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.PositiveSmallIntegerField(choices=[(1, 'Turno 1'), (2, 'Turno 2'), (3, 'Turno 3')])),
            ],
            options={
                'ordering': ['-fecha', 'turno'],
                'unique_together': {('fecha', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='EjercicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizaciones', to='asistencia.ejercicio')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_realizados', to='asistencia.jugador')),
            ],
            options={
                'ordering': ['-fecha', 'jugador__apellido', 'ejercicio__categoria', 'ejercicio__nombre'],
                'unique_together': {('jugador', 'fecha', 'ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistio', 'Asistió'), ('ausente', 'Ausente'), ('tarde', 'Tarde')], default='pendiente', max_length=20)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.entrenamiento')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.jugador')),
            ],
            options={
                'ordering': ['jugador__apellido', 'jugador__nombre'],
                'unique_together': {('jugador', 'entrenamiento')},
            },
        ),
    ]
