# Generated by Django 6.0.3 on 2026-06-09 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenamientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
