# Generated by Django 6.0.3 on 2026-06-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_entrenamiento_entrenador_entrenamiento_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.PositiveIntegerField(verbose_name='Número de cambio')),
                ('tipo', models.CharField(choices=[('pareja', 'Pareja'), ('multipelota', 'Multipelota'), ('entrenador', 'Con entrenador'), ('libre', 'Libre / descanso'), ('otro', 'Otro')], default='pareja', max_length=20)),
                ('detalle', models.CharField(blank=True, help_text='Ejemplo: recepción, saque y tercera pelota, trabajo físico, etc.', max_length=200, verbose_name='Detalle')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='asistencia.entrenamiento')),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_principales', to='asistencia.jugador', verbose_name='Jugador')),
                ('jugador_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_secundarios', to='asistencia.jugador', verbose_name='Compañero')),
            ],
            options={
                'verbose_name': 'Trabajo del turno',
                'verbose_name_plural': 'Trabajos del turno',
                'ordering': ['cambio', 'id'],
            },
        ),
    ]
