# Generated by Django 6.0.3 on 2026-06-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_trabajoturno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Observación')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_jugadores', to='asistencia.entrenamiento')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='asistencia.jugador')),
            ],
            options={
                'verbose_name': 'Observación de jugador',
                'verbose_name_plural': 'Observaciones de jugadores',
                'ordering': ['-creada_el'],
            },
        ),
    ]
