# Generated by Django 6.0.3 on 2026-06-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_observacionjugador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('entrenamiento', 'jugador')},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='detalle_ausencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='motivo_ausencia',
            field=models.CharField(blank=True, choices=[('enfermedad', 'Enfermedad'), ('viaje', 'Viaje'), ('competencia', 'Competencia'), ('estudio', 'Estudio'), ('sin_aviso', 'Sin aviso'), ('otro', 'Otro')], default='', max_length=20),
        ),
    ]
