# Generated by Django 6.0.3 on 2026-06-26 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='', help_text='Ejemplo: partido final del turno o partido de entrenamiento.', max_length=255)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='asistencia.entrenamiento')),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_jugador_1', to='asistencia.jugador')),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_jugador_2', to='asistencia.jugador')),
            ],
            options={
                'verbose_name': 'Partido del turno',
                'verbose_name_plural': 'Partidos del turno',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SetPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('puntos_jugador_1', models.PositiveIntegerField()),
                ('puntos_jugador_2', models.PositiveIntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='asistencia.partidoturno')),
            ],
            options={
                'verbose_name': 'Set del partido',
                'verbose_name_plural': 'Sets del partido',
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('partido', 'numero'), name='set_unico_por_partido')],
            },
        ),
    ]
