# Generated by Django 6.0.3 on 2026-07-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_entrenamiento_finalizado_entrenamiento_finalizado_el_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_realizados', to='asistencia.ejercicio')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_turno', to='asistencia.entrenamiento')),
            ],
            options={
                'verbose_name': 'Ejercicio del turno',
                'verbose_name_plural': 'Ejercicios del turno',
                'ordering': ['entrenamiento__fecha', 'entrenamiento__turno', 'ejercicio__categoria', 'ejercicio__nombre'],
                'unique_together': {('entrenamiento', 'ejercicio')},
            },
        ),
    ]
