# Generated by Django 6.0.3 on 2026-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_entrenador_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='detalle_no_entrenamiento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='motivo_no_entrenamiento',
            field=models.CharField(blank=True, choices=[('feriado', 'Feriado'), ('torneo', 'Torneo'), ('club_cerrado', 'Club cerrado'), ('viaje', 'Viaje'), ('suspendido', 'Suspendido'), ('otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='no_se_entreno',
            field=models.BooleanField(default=False),
        ),
    ]
